apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-svc
  labels:
    app: welcome-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-svc
  template:
    metadata:
      labels:
        app: welcome-svc
    spec:
      containers:
        - name: welcome-svc
          image: ghcr.io/flawmop/welcome-svc
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          resources:
            requests:
              memory: 600Mi
            limits:
              memory: 750Mi
          volumeMounts:
            - name: welcome-config-volume
              mountPath: /workspace/config
      volumes:
        - name: welcome-config-volume
          configMap:
            name: welcome-config
