apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: welcome-config
    files:
      - application.yml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: welcome-svc
