apiVersion: v1
kind: Service
metadata:
  name: welcome-svc
  labels:
    app: welcome-svc
spec:
  type: ClusterIP
  selector:
    app: welcome-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
